name: KGG375_AT3
channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - pandas
  - rasterio
  - rioxarray
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - esda
  - libpysal
  - matplotlib
  - plotly
  - leafmap
  - jupyterlab
  - whitebox
  - pip
  - pip:
      - pystac-client
      - odc-stac
      - pykrige
